/**
 * TD(λ) value network v2: v1's features plus a phase-gated die-face block.
 *
 * v1 (tdnet.ts) deliberately excludes die faces so that roll-phase afterstates
 * are implicit expectations over rolls. That is right where dice are about to
 * be re-rolled, but it throws information away wherever faces are known and
 * frozen: platter/field dice during the active turn (they feed later +1
 * decisions and the blue+white sum), the endTurn phase (no more rolls this
 * turn — all six faces are fixed and determine every remaining +1 option),
 * and the whole passive turn after the platter roll (passivePick /
 * passiveEndTurn).
 *
 * v2 appends 53 features to v1's 163 (total 216):
 *  - 36: per-die face one-hot (6 dice × faces 1..6), active only when the
 *    die's face is frozen for this state: die not in 'pool', or phase ∈
 *    {endTurn, passivePick, passiveEndTurn}. Unrolled faces (0) stay off.
 *  - 6: per-die "face known" mask bit (same gate).
 *  - 11: blue+white sum one-hot (2..12), active only when both faces are
 *    known — this is exactly the value a blue placement would score.
 *
 * Everything else (net shape, afterstate-argmax policy, terminal handling)
 * mirrors v1; the MLP/backprop code is imported from tdnet.ts unchanged.
 * Weights live in tdnetv2-weights.ts, generated by scripts/train-td-v2.ts.
 */
import {
  applyAction,
  getPending,
  scoreState,
  type Action,
  type GameState,
  type VariantDef,
} from '../engine';
import type { Strategy } from './types';
import {
  createEvalCtx,
  extractFeatures,
  forward,
  netFromParams,
  TD_FEATURES,
  type EvalCtx,
  type TdNetParams,
} from './tdnet';
import { TDNETV2_WEIGHTS } from './tdnetv2-weights';

// ---------------------------------------------------------------------------
// Feature extraction
// ---------------------------------------------------------------------------

/** v1's 163 features + 36 face one-hots + 6 known-mask bits + 11 sum one-hots. */
export const TD2_FEATURES = TD_FEATURES + 53;

/** Faces are frozen for the rest of the turn in these phases (no more rolls). */
function facesFrozenPhase(s: GameState): boolean {
  return s.phase === 'endTurn' || s.phase === 'passivePick' || s.phase === 'passiveEndTurn';
}

/**
 * Encode a state into `x` (length TD2_FEATURES). The first TD_FEATURES slots
 * are exactly v1's encoding; the face block follows.
 */
export function extractFeaturesV2(s: GameState, v: VariantDef, x: Float64Array): void {
  extractFeatures(s, v, x); // zero-fills the whole buffer, writes [0, TD_FEATURES)
  const k = TD_FEATURES;
  const phaseFrozen = facesFrozenPhase(s);
  const known = (die: number): boolean => {
    if (die < 0 || die >= s.loc.length) return false;
    const f = s.faces[die];
    return f >= 1 && f <= 6 && (phaseFrozen || s.loc[die] !== 'pool');
  };
  const n = Math.min(6, s.loc.length);
  for (let i = 0; i < n; i++) {
    if (known(i)) {
      x[k + i * 6 + (s.faces[i] - 1)] = 1; // face one-hot
      x[k + 36 + i] = 1; // face-known mask
    }
  }
  const wi = v.colors.indexOf('white');
  const bi = v.colors.indexOf('blue');
  if (known(wi) && known(bi)) {
    x[k + 42 + (s.faces[wi] + s.faces[bi] - 2)] = 1; // blue+white sum 2..12
  }
}

// ---------------------------------------------------------------------------
// Value-based policy (v1's argmax machinery over the v2 encoding)
// ---------------------------------------------------------------------------

/** V(state) on the score/300 scale; terminal states use the real score. */
export function stateValue2(ctx: EvalCtx, s: GameState, v: VariantDef): number {
  if (s.phase === 'over') return scoreState(s, v).total / 300;
  extractFeaturesV2(s, v, ctx.x);
  return forward(ctx.net, ctx.x, ctx.h1, ctx.h2);
}

/** Resolve queued bonus decisions by one-step V argmax. */
export function resolvePendingByValue2(ctx: EvalCtx, s: GameState, v: VariantDef): GameState {
  let cur = s;
  let guard = 0;
  while (cur.pending.length > 0 && guard++ < 64) {
    const node = getPending(cur, v);
    if (node.kind !== 'decision') break;
    let best: GameState | null = null;
    let bestVal = -Infinity;
    for (const a of node.actions) {
      const ns = applyAction(cur, v, a);
      const val = stateValue2(ctx, ns, v);
      if (val > bestVal) {
        bestVal = val;
        best = ns;
      }
    }
    if (!best) break;
    cur = best;
  }
  return cur;
}

/** Afterstate argmax over V; the policy for td-net-v2 and its trainer. */
export function chooseByValue2(
  ctx: EvalCtx,
  s: GameState,
  v: VariantDef,
  actions: Action[],
): Action {
  let best = actions[0];
  let bestVal = -Infinity;
  for (const a of actions) {
    const ns = resolvePendingByValue2(ctx, applyAction(s, v, a), v);
    const val = stateValue2(ctx, ns, v);
    if (val > bestVal) {
      bestVal = val;
      best = a;
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// Strategy factory
// ---------------------------------------------------------------------------

export interface TdNetV2Opts {
  params?: TdNetParams;
  name?: string;
}

export function makeTdNetV2(opts: TdNetV2Opts = {}): Strategy {
  const ctx = createEvalCtx(netFromParams(opts.params ?? TDNETV2_WEIGHTS));
  return {
    name: opts.name ?? 'td-net-v2',
    choose(state, actions, c) {
      if (actions.length === 1) return actions[0];
      return chooseByValue2(ctx, state, c.variant, actions);
    },
  };
}

/** Leaf evaluation on the score scale, for expectimax's `evalFn`. */
export function makeTdNetV2Eval(params?: TdNetParams): (s: GameState, v: VariantDef) => number {
  const ctx = createEvalCtx(netFromParams(params ?? TDNETV2_WEIGHTS));
  return (s, v) => 300 * stateValue2(ctx, s, v);
}
