/**
 * TD(λ) value network "bonus": v1's features plus an explicit bonus-economy
 * block — the "reward chasing" hypothesis.
 *
 * v1's encoding already carries group completion fractions, but the net must
 * derive the cascade structure itself: which bonus a group grants, how close
 * each printed bonus is to firing, and how productive the bonus engine has
 * been so far. This variant spells those out so they are linearly visible:
 *
 *  - 2: lifetime action-bar unlocks (reroll, +1), /7 — bonus production to
 *    date, invisible in v1 which only sees the *unspent* counters.
 *  - 1: completed bonus-carrying groups, /12.
 *  - 8: "one-away" counts per bonus kind — groups exactly one cell from
 *    firing, the cascade trigger signal (capped at 2, /2). Kind channels:
 *    reroll, +1, fox, X-yellow, X-blue, X-green, write-orange, write-purple.
 *  - 8: write-track "pull" per bonus kind — Σ 1/(1+d) over bonus-carrying
 *    slots at distance d from each track's next fill (capped at 1).
 *
 * 19 extra features, 182 total. Everything else (net shape, afterstate-argmax
 * policy, terminal handling) mirrors v1; MLP code is imported unchanged.
 * Weights live in tdnet-bonus-weights.ts (generated by the parallel trainer
 * with --features v1bonus).
 */
import {
  applyAction,
  getPending,
  scoreState,
  type Action,
  type Effect,
  type GameState,
  type VariantDef,
} from '../engine';
import type { Strategy } from './types';
import {
  createEvalCtx,
  extractFeatures,
  forward,
  netFromParams,
  TD_FEATURES,
  type EvalCtx,
  type TdNetParams,
} from './tdnet';
import { TDNET_BONUS_WEIGHTS } from './tdnet-bonus-weights';

// ---------------------------------------------------------------------------
// Feature extraction
// ---------------------------------------------------------------------------

/** v1's 163 features + 2 banked + 1 completed + 8 one-away + 8 track pull. */
export const TD_BONUS_FEATURES = TD_FEATURES + 19;

/** Bonus-kind channel of an effect, or -1 if untracked. */
function kindOf(e: Effect): number {
  switch (e.t) {
    case 'reroll':
      return 0;
    case 'plus1':
      return 1;
    case 'fox':
      return 2;
    case 'crossAny':
    case 'crossNext':
      return e.area === 'yellow' ? 3 : e.area === 'blue' ? 4 : 5;
    case 'writeNext':
      return e.area === 'orange' ? 6 : 7;
    default:
      return -1;
  }
}

/**
 * Encode a state into `x` (length TD_BONUS_FEATURES). The first TD_FEATURES
 * slots are exactly v1's encoding; the bonus-economy block follows.
 */
export function extractFeaturesBonus(s: GameState, v: VariantDef, x: Float64Array): void {
  extractFeatures(s, v, x); // zero-fills the whole buffer, writes [0, TD_FEATURES)
  const k = TD_FEATURES;

  x[k] = Math.min(7, s.barUnlocks.reroll) / 7;
  x[k + 1] = Math.min(7, s.barUnlocks.plus1) / 7;

  let completed = 0;
  const oneAway = k + 3;
  const pull = k + 11;
  for (const area of v.areas) {
    const cells = s.areas[area.id];
    const ui = area.ui;

    if (ui.groups) {
      for (const g of ui.groups) {
        if (!g.bonus) continue;
        const kind = kindOf(g.bonus);
        if (kind < 0) continue;
        let done = 0;
        for (const c of g.cells) if (cells[c] !== 0) done++;
        if (done === g.cells.length) completed++;
        else if (done === g.cells.length - 1) x[oneAway + kind] = Math.min(1, x[oneAway + kind] + 0.5);
      }
    }

    if (ui.kind === 'track') {
      const next = cells.findIndex((c) => c === 0);
      if (next < 0) continue;
      for (let i = next; i < ui.cells.length; i++) {
        const b = ui.cells[i].bonus;
        if (!b) continue;
        const kind = kindOf(b);
        if (kind < 0) continue;
        x[pull + kind] = Math.min(1, x[pull + kind] + 1 / (1 + (i - next)));
      }
    }
  }
  x[k + 2] = Math.min(12, completed) / 12;
}

// ---------------------------------------------------------------------------
// Value-based policy (v1's argmax machinery over the bonus encoding)
// ---------------------------------------------------------------------------

/** V(state) on the score/300 scale; terminal states use the real score. */
export function stateValueBonus(ctx: EvalCtx, s: GameState, v: VariantDef): number {
  if (s.phase === 'over') return scoreState(s, v).total / 300;
  extractFeaturesBonus(s, v, ctx.x);
  return forward(ctx.net, ctx.x, ctx.h1, ctx.h2);
}

/** Resolve queued bonus decisions by one-step V argmax. */
export function resolvePendingByValueBonus(ctx: EvalCtx, s: GameState, v: VariantDef): GameState {
  let cur = s;
  let guard = 0;
  while (cur.pending.length > 0 && guard++ < 64) {
    const node = getPending(cur, v);
    if (node.kind !== 'decision') break;
    let best: GameState | null = null;
    let bestVal = -Infinity;
    for (const a of node.actions) {
      const ns = applyAction(cur, v, a);
      const val = stateValueBonus(ctx, ns, v);
      if (val > bestVal) {
        bestVal = val;
        best = ns;
      }
    }
    if (!best) break;
    cur = best;
  }
  return cur;
}

/** Afterstate argmax over V; the policy for td-net-bonus and its trainer. */
export function chooseByValueBonus(
  ctx: EvalCtx,
  s: GameState,
  v: VariantDef,
  actions: Action[],
): Action {
  let best = actions[0];
  let bestVal = -Infinity;
  for (const a of actions) {
    const ns = resolvePendingByValueBonus(ctx, applyAction(s, v, a), v);
    const val = stateValueBonus(ctx, ns, v);
    if (val > bestVal) {
      bestVal = val;
      best = a;
    }
  }
  return best;
}

// ---------------------------------------------------------------------------
// Strategy factory
// ---------------------------------------------------------------------------

export interface TdNetBonusOpts {
  params?: TdNetParams;
  name?: string;
}

export function makeTdNetBonus(opts: TdNetBonusOpts = {}): Strategy {
  const ctx = createEvalCtx(netFromParams(opts.params ?? TDNET_BONUS_WEIGHTS));
  return {
    name: opts.name ?? 'td-net-bonus',
    choose(state, actions, c) {
      if (actions.length === 1) return actions[0];
      return chooseByValueBonus(ctx, state, c.variant, actions);
    },
  };
}
