/**
 * Export a training checkpoint's best net as a weights module.
 *
 *   npx tsx scripts/export-weights.ts checkpoints/td-twice-polish.json \
 *     src/strategies/tdnet-twice-weights.ts TDNET_TWICE_WEIGHTS
 *
 * The trainer writes its own weights file when a run ends; this does the same
 * from a checkpoint mid-run, so a good net can be shipped without stopping
 * training. Exports `bestParams` (the best frozen-eval snapshot), falling back
 * to the live params when no eval has beaten the resume point yet.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import type { TdNetParams } from '../src/strategies/tdnet';

const [ckPath, outPath, constName] = process.argv.slice(2);
if (!ckPath || !outPath || !constName) {
  throw new Error('usage: export-weights.ts <checkpoint.json> <out.ts> <CONST_NAME>');
}

interface Checkpoint {
  episode: number;
  bestMean: number;
  params: TdNetParams;
  bestParams: TdNetParams | null;
}

const ck = JSON.parse(readFileSync(ckPath, 'utf8')) as Checkpoint;
const p = ck.bestParams ?? ck.params;
const arr = (a: number[]) => `[${a.map((x) => Number(x.toPrecision(5))).join(',')}]`;

writeFileSync(
  outPath,
  `/**
 * Trained TD(λ) value-network weights — GENERATED by scripts/export-weights.ts
 * from ${ckPath} @ episode ${ck.episode}, best frozen eval ${ck.bestMean.toFixed(1)}.
 */
import type { TdNetParams } from './tdnet';

export const ${constName}: TdNetParams = {
  nIn: ${p.nIn},
  nH1: ${p.nH1},
  nH2: ${p.nH2},
  W1: ${arr(p.W1)},
  b1: ${arr(p.b1)},
  W2: ${arr(p.W2)},
  b2: ${arr(p.b2)},
  W3: ${arr(p.W3)},
  b3: ${Number(p.b3.toPrecision(5))},
};
`,
);
console.log(`wrote ${outPath} (${constName}, ep ${ck.episode}, best ${ck.bestMean.toFixed(1)})`);
